### ISSUE TITLE
Syntax error in ubuntu 20.04 with python3.8

### ISSUE THREAD

**Issue by chenchix** [gdude2002/melcloud#1]
Installed from pip3 and run the exmample in repo:

Traceback (most recent call last):
  File "./melcloud_temp.py", line 3, in <module>
    from melcloud import MELCloud, AsyncConnection
  File "/home/chencho/.local/lib/python3.8/site-packages/melcloud/__init__.py", line 2
    from melcloud.async.connection import AsyncConnection
                  ^
SyntaxError: invalid syntax

**Comment by gdude2002** [comment]
Hey, thanks for the issue!

The problem here is that `async` was made a reserved keyword in a version of Python released after this was written.

However, it hasn't been touched in some time - you may have better luck with [PyMelcloud](https://pypi.org/project/pymelcloud/).

If I end up getting some time, though, I'll address this issue.

**Comment by chenchix** [comment]
Thank you. Will give a try!
